query User($username: String, $userid: Int) {
  User(name: $username, id: $userid) {
    id
    name
    avatar {
      large
      medium
    }
    bannerImage
    siteUrl
    createdAt
    favourites {
      anime {
        nodes {
          id
          title {
            romaji
            english
            native
            userPreferred
          }
        }
      }
      manga {
        nodes {
          id
          title {
            romaji
            english
            native
            userPreferred
          }
        }
      }
    }
    options {
      profileColor
    }
    statistics {
      anime {
        count
        meanScore
      }
      manga {
        count
        meanScore
      }
    }
  }
}
